// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjhwhLDmIXtivf0W0_T27CnWADPftU_lg',
    appId: '1:453300020503:android:fce94d0b5d777e8d970352',
    messagingSenderId: '453300020503',
    projectId: 'crud-firebase-9d881',
    databaseURL: 'https://crud-firebase-9d881-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-9d881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKV6dG44b6Jnro-xRAfMvLaZbHYyAJHU',
    appId: '1:453300020503:ios:b6b76513afa30415970352',
    messagingSenderId: '453300020503',
    projectId: 'crud-firebase-9d881',
    databaseURL: 'https://crud-firebase-9d881-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-9d881.appspot.com',
    iosBundleId: 'com.example.appTarefasFb',
  );
}
